glu/blog/urls.py
from django.urls import path
from .views import Post_List,Detail_View


app_name="blog"

urlpatterns=[
    path('',Post_List.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", Post_List.as_view(), name="post_list_by_tag"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", Detail_View.as_view(), name="post-detail"),
]

glu/glu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include("home.urls",namespace="home")),
    
    path('blog/',include("blog.urls",namespace="blog")),
]

glu/home/urls.py
from django.urls import path
from .views import Home

app_name="home"

urlpatterns=[
    path('',Home.as_view(),name="home_page")
]

glu/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.

class PostManager(models.Manager):
    def get_queryset(self) :
        return super().get_queryset().filter(status=Post.Status.PUBLISH)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT="DR","Draft"
        PUBLISH="PB","Publish"

    tags=TaggableManager()
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_post")
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(choices=Status.choices,default=Status.DRAFT,max_length=2)
    
    published=PostManager()
    objects=models.Manager()



    class Meta:
        ordering=['-publish']
        indexes=[models.Index(fields=['-publish'])]


    def get_absolute_url(self):
        return reverse("blog:post-detail",args=[self.publish.year,
         self.publish.month,self.publish.day,self.slug])

    def __str__(self) :
        return f"{self.title}"

glu/home/models.py
from django.db import models

# Create your models here.

glu/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DetailView
from .models import Post
from taggit.models import Tag

# Create your views here.


class Post_List(ListView):
    template_name="posts/posts.html"
    context_object_name="posts"
    

    def get_queryset(self,tag_slug=None):
        query1=Post.published.all()
        tag_slug=self.kwargs.get("tag_slug")
        if tag_slug:
            query2=get_object_or_404(Tag,slug=tag_slug)
            query1=query1.filter(tags__in=[query2])


        return query1

    def get_context_data(self, **kwargs: Any):
        context=super().get_context_data(**kwargs)
        context['tags']=self.kwargs.get("tag_slug")

        return context


class Detail_View(DetailView):
    template_name="posts/detail.html"
    context_object_name="post"
    
    def get_object(self, queryset=None):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        post_slug = self.kwargs.get('post')
        
        return get_object_or_404(
            Post,
            slug=post_slug,
            publish__year=year,
            publish__month=month,
            publish__day=day,
            status=Post.Status.PUBLISH
        )

glu/home/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.base import TemplateView
from blog.models import Post


# Create your views here.

class Home(TemplateView):
    template_name="index.html"
    
    def get_context_data(self, **kwargs: Any) :
        context=super().get_context_data(**kwargs)
        context["data"]=Post.published.all()[0:3]

        return context
    

glu/blog/templates/base.html
{%load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{block title}{endblock}</title>
 
</head>
<body>
    <div class="container">
        <h1>My Blog</h1>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>
    <a href="{% url 'home:home_page' %}">go back home</a>
</body>
</html>

glu/blog/templates/posts/detail.html
{% extends 'base.html' %}
{% block title %}{{post.title}}{%endblock%}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{post.body}}</p>
{% endblock %}

glu/blog/templates/posts/posts.html
{% extends "base.html" %}
{% block title %}My Blog {% endblock %}

{% block content %}
    <div style="border: 2px solid blueviolet; border-radius: 1rem;margin: 2rem; padding: 2rem;">
    {% for post in posts %}

        <h2 style="border-bottom: 5px solid rgb(200, 176, 223);"><a href={{post.get_absolute_url}}>{{post.title}}</a></h2>
        <p style="color: brown;">published by <strong><em>{{post.author}}</em></strong> on {{post.created}}</p>
        <p>{{post.body| truncatewords:25|linebreaks}}</p>
        <p>Tags : 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <hr>
    {% endfor %}
    </div>
{% endblock %}

glu/home/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Basic HTML Template</title>
</head>
<body>
    <div class="head-wrapper">
    <header>
        <div class="icons">
            <ul>
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>4</li>
            </ul>
        </div>
        <div class="contacts">
            <span>CALL US- 061 012 1251</span>
            <span>|</span>
            <span>MON-FRI </span>
        </div>
    </header>
    </div>
    
    <nav>
        <div class="links">
            <ul>
                <li>Home</li>
                <li><a href="{% url 'blog:post_list' %}">blog</a></li>
                <li>contact</li>
                <li>more</li>
            </ul>
        </div>
        
        <div class="logo">
            <p>LOGO</p>
        </div>

        <div class="search">
            <input type="text">
        </div>
    </nav>

    <div class="front-wrapper">
        
    <div class="front">
        <button style="background-color: aquamarine;padding: .5rem;">LIFESTYLE</button>
        <p style="font-size: 2.2rem;font-weight: 800;">Lorem ipsum dolor sit amet consectetur, adipisicing elit. </p>
        <hr>
        <p style="font-size: small;">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate eveniet quae fuga, totam culpa quis</p>
    </div>
    </div>


    <div class="editors-choice">
        <div>
            <img src="{% static 'pic1.png' %}" alt="save">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <p>Date</p>
        </div>
    
        <div>
            <img src="{% static 'pic1.png' %}" alt="save">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <p>Date</p>
        </div>

        <div>
            <img src="{% static 'pic1.png' %}" alt="save">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <p>Date</p>
        </div>
    </div>

    <div class="second-wrapper">
        
        <div class="front">
            <button style="background-color: aquamarine;padding: .5rem;">LIFESTYLE</button>
            <p style="font-size: 2.2rem;font-weight: 800;">Lorem ipsum dolor sit amet consectetur, adipisicing elit. </p>
            <hr>
            <p style="font-size: small;">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate eveniet quae fuga, totam culpa quis</p>
        </div>
        </div>


        <div class="pass">
            {% for post in data %}
            <div class="pass">
                <h1>{{post.title}}</h1>
                <p>{{post.body|truncatewords:20}}</p>
            </div>
            {% endfor %}
        </div>

    <footer>
        <p>subscribe to our news letter</p>
        <form> <input type="text"> <button type="submit">subscribe</button></form>
        <p class="poli">
            <ul>
                <li>politics</li>
                <li>shame</li>
                <li>hire</li>
                <li>hays</li>
            </ul>
        </p>

        <p>copyRight</p>
    </footer>
</body>
</html>